// protoc --go_out=plugins=grpc:. *.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.0
// source: pay/v1/pay.proto

package v1

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PayReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderId      string `protobuf:"bytes,1,opt,name=OrderId,proto3" json:"OrderId,omitempty" v:"required"`           // v: required
	OrderPayInfo string `protobuf:"bytes,2,opt,name=OrderPayInfo,proto3" json:"OrderPayInfo,omitempty" v:"required"` // v: required
}

func (x *PayReq) Reset() {
	*x = PayReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pay_v1_pay_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PayReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayReq) ProtoMessage() {}

func (x *PayReq) ProtoReflect() protoreflect.Message {
	mi := &file_pay_v1_pay_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayReq.ProtoReflect.Descriptor instead.
func (*PayReq) Descriptor() ([]byte, []int) {
	return file_pay_v1_pay_proto_rawDescGZIP(), []int{0}
}

func (x *PayReq) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *PayReq) GetOrderPayInfo() string {
	if x != nil {
		return x.OrderPayInfo
	}
	return ""
}

type PayRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PayRes) Reset() {
	*x = PayRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pay_v1_pay_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PayRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayRes) ProtoMessage() {}

func (x *PayRes) ProtoReflect() protoreflect.Message {
	mi := &file_pay_v1_pay_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayRes.ProtoReflect.Descriptor instead.
func (*PayRes) Descriptor() ([]byte, []int) {
	return file_pay_v1_pay_proto_rawDescGZIP(), []int{1}
}

var File_pay_v1_pay_proto protoreflect.FileDescriptor

var file_pay_v1_pay_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x61, 0x79, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x61, 0x79, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x03, 0x70, 0x61, 0x79, 0x22, 0x46, 0x0a, 0x06, 0x50, 0x61, 0x79, 0x52, 0x65,
	0x71, 0x12, 0x18, 0x0a, 0x07, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x50, 0x61, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x50, 0x61, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x22,
	0x08, 0x0a, 0x06, 0x50, 0x61, 0x79, 0x52, 0x65, 0x73, 0x32, 0x2b, 0x0a, 0x03, 0x50, 0x61, 0x79,
	0x12, 0x24, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x0b, 0x2e, 0x70, 0x61, 0x79,
	0x2e, 0x50, 0x61, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x0b, 0x2e, 0x70, 0x61, 0x79, 0x2e, 0x50, 0x61,
	0x79, 0x52, 0x65, 0x73, 0x22, 0x00, 0x42, 0x2b, 0x5a, 0x29, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x6f, 0x67, 0x66, 0x2f, 0x67, 0x66, 0x2d, 0x64, 0x65, 0x6d,
	0x6f, 0x2d, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pay_v1_pay_proto_rawDescOnce sync.Once
	file_pay_v1_pay_proto_rawDescData = file_pay_v1_pay_proto_rawDesc
)

func file_pay_v1_pay_proto_rawDescGZIP() []byte {
	file_pay_v1_pay_proto_rawDescOnce.Do(func() {
		file_pay_v1_pay_proto_rawDescData = protoimpl.X.CompressGZIP(file_pay_v1_pay_proto_rawDescData)
	})
	return file_pay_v1_pay_proto_rawDescData
}

var file_pay_v1_pay_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pay_v1_pay_proto_goTypes = []interface{}{
	(*PayReq)(nil), // 0: pay.PayReq
	(*PayRes)(nil), // 1: pay.PayRes
}
var file_pay_v1_pay_proto_depIdxs = []int32{
	0, // 0: pay.Pay.Create:input_type -> pay.PayReq
	1, // 1: pay.Pay.Create:output_type -> pay.PayRes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pay_v1_pay_proto_init() }
func file_pay_v1_pay_proto_init() {
	if File_pay_v1_pay_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pay_v1_pay_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PayReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pay_v1_pay_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PayRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pay_v1_pay_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pay_v1_pay_proto_goTypes,
		DependencyIndexes: file_pay_v1_pay_proto_depIdxs,
		MessageInfos:      file_pay_v1_pay_proto_msgTypes,
	}.Build()
	File_pay_v1_pay_proto = out.File
	file_pay_v1_pay_proto_rawDesc = nil
	file_pay_v1_pay_proto_goTypes = nil
	file_pay_v1_pay_proto_depIdxs = nil
}
